---
configure_explorer: true
configure_hostname: false
custom_hostname: windows-ansible
configure_start_menu: true
configure_taskbar: true
disable_mouse_acceleration: true
remote_desktop_enabled: true
remove_desktop_icons: false
set_sound_scheme: true

install_windows_updates: true
windows_updates_reboot: true
update_categories:
  # You can install only specific updates by uncommenting it
  # * - installs all updates
  # - "*"
  - Critical Updates
  # - Definition Updates
  # - Developer Kits
  # - Feature Packs
  - Security Updates
  # - Service Packs
  # - Tools
  - Update Rollups
  # - Updates
  # - Upgrades

change_power_plan: true
# high_performance
# balanced
# power_saver
power_plan: "high_performance"

choco_installed_packages:
  - name: adobereader
    state: latest

  - name: 7zip
    state: latest

  - name: advanced-ip-scanner
    state: latest

  ## installs awscli, but won't update it
  - name: awscli
    state: latest

  - name: azure-cli
    state: latest

  - name: bitwarden
    state: absent

  - name: brave
    state: latest

  - name: caffeine
    state: absent

  - name: docker-desktop
    state: latest

  - name: firacodenf
    state: latest

    # installs latest version of the Firefox while ignoring the package checksum
  - name: Firefox
    state: latest
    choco_args: --ignorechecksum

  - name: git
    state: latest

  # - name: git.install
  #   state: latest

  - name: github-desktop
    state: absent

  # - name: GoogleChrome
  #   state: latest

  - name: golang
    state: absent

  - name: greenshot
    state: latest

  - name: hackfont
    state: latest

  - name: irfanview
    state: latest

  - name: jre8
    state: absent

  - name: kubernetes-cli
    state: latest

  - name: lens
    state: latest

  # - name: microsoft-windows-terminal
  #   state: latest

  - name: notion
    state: latest

  - name: peazip
    state: absent

  - name: pdk
    state: latest

  - name: powertoys
    state: latest

  - name: python3
    state: latest

  - name: sharex
    state: absent

  - name: sops
    state: latest

  - name: sysinternals
    state: latest

  - name: sumatrapdf
    state: absent

  - name: telegram
    state: absent

  - name: telegram.install
    state: absent

  - name: terraform
    state: absent

  - name: vlc
    state: latest

  - name: vscode
    state: latest

  - name: WhatsApp
    state: latest
    choco_args: --ignorechecksum

  - name: zoom
    state: latest

winget_packages:

  - name: "Auto Dark Mode"
    source: winget

  - name: WinDynamicDesktop
    source: winget

install_fonts: true
installed_nerdfonts:
  - FiraCode
  - FantasqueSansMono

install_ohmyposh: true

# List of features: "Get-WindowsOptionalFeature -Online"
install_windows_features: false
windows_features:
  Microsoft-Hyper-V: true

# List of valid distributions that can be installed:
# wsl-alpine
# wsl-archlinux
# wsl-debiangnulinux
# wsl-fedoraremix
# wsl-kalilinux
# wsl-opensuse
# wsl-sles
# wsl-ubuntu-1604
# wsl-ubuntu-1804
# wsl-ubuntu-2004
install_wsl2: true
wsl2_distribution: wsl-ubuntu-2204

remove_bloatware: true
bloatware:
  - Microsoft.BingNews
  - Microsoft.BingWeather
  - Microsoft.GamingApp
  - Microsoft.GetHelp
  - Microsoft.Getstarted
  # - Microsoft.Messaging
  - Microsoft.Microsoft3DViewer
  - Microsoft.MicrosoftOfficeHub
  - Microsoft.MicrosoftSolitaireCollection
  - Microsoft.MicrosoftStickyNotes
  - Microsoft.MixedReality.Portal
  # - Microsoft.MSPaint
  - Microsoft.Office.OneNote
  - Microsoft.OneConnect
  - Microsoft.People
  - Microsoft.PowerAutomateDesktop
  - Microsoft.Print3D
  - Microsoft.ScreenSketch
  - Microsoft.SkypeApp
  - Microsoft.Todos
  - Microsoft.Windows.Photos
  - Microsoft.WindowsAlarms
  # - Microsoft.WindowsCalculator
  - Microsoft.Wallet
  - Microsoft.WindowsCamera
  # - microsoft.windowscommunicationsapps
  - Microsoft.WindowsFeedbackHub
  - Microsoft.WindowsMaps
  - Microsoft.WindowsSoundRecorder
  - Microsoft.Xbox
  - Microsoft.Xbox.TCUI
  - Microsoft.XboxApp
  - Microsoft.XboxGameOverlay
  - Microsoft.XboxSpeechToTextOverlay
  # - Microsoft.YourPhone
  - Microsoft.ZuneMusic
  - Microsoft.ZuneVideo
  - MicrosoftTeams

defrag_volumes: true
include_volumes:
  - C
